# Generated by Django 5.1.4 on 2025-02-07 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_for', models.CharField(choices=[('Myself', 'Myself'), ('My Sister', 'My Sister'), ('My Brother', 'My Brother'), ('My Son', 'My Son'), ('My Daughter', 'My Daughter'), ('My Relative', 'My Relative'), ('My Friend', 'My Friend')], max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('phone', models.CharField(max_length=15)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10)),
                ('dob', models.DateField()),
                ('religion', models.CharField(choices=[('Hindu', 'Hindu'), ('Christian', 'Christian'), ('Muslim', 'Muslim')], max_length=20)),
                ('nationality', models.CharField(default='Indian', max_length=20)),
                ('password', models.CharField(max_length=128)),
                ('height', models.IntegerField(choices=[(100, 100), (101, 101), (102, 102), (103, 103), (104, 104), (105, 105), (106, 106), (107, 107), (108, 108), (109, 109), (110, 110), (111, 111), (112, 112), (113, 113), (114, 114), (115, 115), (116, 116), (117, 117), (118, 118), (119, 119), (120, 120), (121, 121), (122, 122), (123, 123), (124, 124), (125, 125), (126, 126), (127, 127), (128, 128), (129, 129), (130, 130), (131, 131), (132, 132), (133, 133), (134, 134), (135, 135), (136, 136), (137, 137), (138, 138), (139, 139), (140, 140), (141, 141), (142, 142), (143, 143), (144, 144), (145, 145), (146, 146), (147, 147), (148, 148), (149, 149), (150, 150), (151, 151), (152, 152), (153, 153), (154, 154), (155, 155), (156, 156), (157, 157), (158, 158), (159, 159), (160, 160), (161, 161), (162, 162), (163, 163), (164, 164), (165, 165), (166, 166), (167, 167), (168, 168), (169, 169), (170, 170), (171, 171), (172, 172), (173, 173), (174, 174), (175, 175), (176, 176), (177, 177), (178, 178), (179, 179), (180, 180), (181, 181), (182, 182), (183, 183), (184, 184), (185, 185), (186, 186), (187, 187), (188, 188), (189, 189), (190, 190), (191, 191), (192, 192), (193, 193), (194, 194), (195, 195), (196, 196), (197, 197), (198, 198), (199, 199), (200, 200), (201, 201), (202, 202), (203, 203), (204, 204), (205, 205), (206, 206), (207, 207), (208, 208), (209, 209), (210, 210)])),
                ('weight', models.IntegerField(choices=[(40, 40), (41, 41), (42, 42), (43, 43), (44, 44), (45, 45), (46, 46), (47, 47), (48, 48), (49, 49), (50, 50), (51, 51), (52, 52), (53, 53), (54, 54), (55, 55), (56, 56), (57, 57), (58, 58), (59, 59), (60, 60), (61, 61), (62, 62), (63, 63), (64, 64), (65, 65), (66, 66), (67, 67), (68, 68), (69, 69), (70, 70), (71, 71), (72, 72), (73, 73), (74, 74), (75, 75), (76, 76), (77, 77), (78, 78), (79, 79), (80, 80), (81, 81), (82, 82), (83, 83), (84, 84), (85, 85), (86, 86), (87, 87), (88, 88), (89, 89), (90, 90), (91, 91), (92, 92), (93, 93), (94, 94), (95, 95), (96, 96), (97, 97), (98, 98), (99, 99), (100, 100), (101, 101), (102, 102), (103, 103), (104, 104), (105, 105), (106, 106), (107, 107), (108, 108), (109, 109), (110, 110)])),
                ('marital_status', models.CharField(choices=[('Never Married', 'Never Married'), ('Divorced', 'Divorced'), ('Annulled', 'Annulled'), ('Widowed', 'Widowed'), ('Nikah Divorce', 'Nikah Divorce'), ('Awaiting Divorce', 'Awaiting Divorce'), ('Separated', 'Separated')], max_length=20)),
                ('body_type', models.CharField(choices=[('Slim', 'Slim'), ('Fit', 'Fit'), ('Toned', 'Toned'), ('Short', 'Short'), ('Average', 'Average'), ('Tall', 'Tall'), ('Plus Size', 'Plus Size'), ('Big and Tall', 'Big and Tall'), ('Chubby', 'Chubby')], max_length=20)),
                ('physically_challenged', models.BooleanField(default=False)),
                ('highest_education', models.CharField(choices=[('Doctorate', 'Doctorate'), ('Masters', 'Masters'), ('Bachelors', 'Bachelors'), ('Diploma', 'Diploma'), ('High/Secondary School', 'High/Secondary School'), ('Less than High School', 'Less than High School')], default='Not Specified', max_length=30)),
                ('course', models.CharField(choices=[('MCA', 'MCA'), ('MBA', 'MBA'), ('MCom', 'MCom'), ('MArch', 'MArch'), ('Audiology', 'Audiology'), ('IPS', 'IPS'), ('IAS', 'IAS'), ('IRS', 'IRS'), ('MSc Nursing', 'MSc Nursing'), ('MSc Agriculture', 'MSc Agriculture'), ('MPharm', 'MPharm')], max_length=30)),
                ('country', models.CharField(default='India', max_length=20)),
                ('state', models.CharField(default='Kerala', max_length=20)),
                ('district', models.CharField(choices=[('Thrissur', 'Thrissur'), ('Ernakulam', 'Ernakulam'), ('Kottayam', 'Kottayam'), ('Kannur', 'Kannur'), ('Kasargod', 'Kasargod'), ('Thiruvananthapuram', 'Thiruvananthapuram'), ('Idukki', 'Idukki'), ('Wayanad', 'Wayanad'), ('Pathanamthitta', 'Pathanamthitta'), ('Palakkad', 'Palakkad'), ('Malappuram', 'Malappuram'), ('Kollam', 'Kollam'), ('Alappuzha', 'Alappuzha'), ('Kozhikode', 'Kozhikode')], max_length=20)),
                ('city', models.CharField(choices=[('Neyyattinkara', 'Neyyattinkara'), ('Varkala', 'Varkala'), ('Aluva', 'Aluva'), ('Angamaly', 'Angamaly'), ('Perumbavoor', 'Perumbavoor'), ('Feroke', 'Feroke'), ('Kunnamangalam', 'Kunnamangalam'), ('Guruvayur', 'Guruvayur'), ('Chalakudy', 'Chalakudy'), ('Karunagappally', 'Karunagappally'), ('Punalur', 'Punalur'), ('Changanassery', 'Changanassery'), ('Pala', 'Pala'), ('Manjeri', 'Manjeri'), ('Tirur', 'Tirur')], max_length=20)),
                ('community', models.CharField(choices=[('Nair', 'Nair'), ('Ezhava', 'Ezhava'), ('Brahmin', 'Brahmin'), ('Vishwakarma', 'Vishwakarma'), ('Scheduled Caste (SC)', 'Scheduled Caste (SC)'), ('Mappila', 'Mappila'), ('Thangal', 'Thangal'), ('Syrian Christian', 'Syrian Christian'), ('Latin Catholic', 'Latin Catholic'), ('Jacobite', 'Jacobite'), ('Marthoma', 'Marthoma'), ('Anglo-Indian', 'Anglo-Indian'), ('Jewish', 'Jewish'), ('Tribal', 'Tribal')], max_length=30)),
                ('financial_status', models.CharField(choices=[('Wealthy', 'Wealthy'), ('Upper Middle Class', 'Upper Middle Class'), ('Lower Middle Class', 'Lower Middle Class'), ('Financially Stable', 'Financially Stable'), ('Inherited Wealth', 'Inherited Wealth'), ('Business Family', 'Business Family'), ('Retired Family Income', 'Retired Family Income'), ('Prefer Not to Say', 'Prefer Not to Say'), ('Well-off', 'Well-off'), ('Working Class', 'Working Class'), ('Affluent', 'Affluent'), ('Struggling Financially', 'Struggling Financially')], max_length=30)),
                ('description', models.TextField()),
                ('photo', models.ImageField(upload_to='profile_photos/')),
            ],
        ),
    ]
