# Generated by Django 5.1.4 on 2025-02-20 04:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matrimony_app', '0003_alter_member_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='company_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='current_job',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='father_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='father_occupation',
            field=models.CharField(blank=True, choices=[('Business', 'Business'), ('Accounts', 'Accounts'), ('IT', 'IT'), ('Engineer', 'Engineer'), ('Doctor', 'Doctor'), ('Other', 'Other')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='father_occupation_other',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='job_location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='mother_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='mother_occupation',
            field=models.CharField(blank=True, choices=[('Business', 'Business'), ('Accounts', 'Accounts'), ('IT', 'IT'), ('Engineer', 'Engineer'), ('Doctor', 'Doctor'), ('Housewife', 'Housewife'), ('Other', 'Other')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='mother_occupation_other',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='siblings',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No'), ('Single Child', 'Single Child')], max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='Sibling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('occupation', models.CharField(choices=[('Studies', 'Studies'), ('Accounts', 'Accounts'), ('IT', 'IT'), ('Business', 'Business'), ('Engineer', 'Engineer'), ('Doctor', 'Doctor'), ('Other', 'Other')], max_length=100)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='siblings_list', to='matrimony_app.member')),
            ],
        ),
    ]
