# Generated by Django 5.1.4 on 2025-02-24 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matrimony_app', '0004_member_company_name_member_current_job_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='company_name',
        ),
        migrations.RemoveField(
            model_name='member',
            name='current_job',
        ),
        migrations.RemoveField(
            model_name='member',
            name='father_name',
        ),
        migrations.RemoveField(
            model_name='member',
            name='father_occupation',
        ),
        migrations.RemoveField(
            model_name='member',
            name='father_occupation_other',
        ),
        migrations.RemoveField(
            model_name='member',
            name='job_location',
        ),
        migrations.RemoveField(
            model_name='member',
            name='mother_name',
        ),
        migrations.RemoveField(
            model_name='member',
            name='mother_occupation',
        ),
        migrations.RemoveField(
            model_name='member',
            name='mother_occupation_other',
        ),
        migrations.RemoveField(
            model_name='member',
            name='siblings',
        ),
        migrations.DeleteModel(
            name='Sibling',
        ),
    ]
