# Generated by Django 5.1.4 on 2025-02-24 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matrimony_app', '0005_remove_member_company_name_remove_member_current_job_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='company_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='current_job',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='father_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='father_occupation',
            field=models.CharField(blank=True, choices=[('Business', 'Business'), ('IT', 'IT'), ('Engineer', 'Engineer'), ('Doctor', 'Doctor'), ('Government Job', 'Government Job'), ('Abroad', 'Abroad'), ('Other', 'Other')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='job_location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='mother_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='mother_occupation',
            field=models.CharField(blank=True, choices=[('Business', 'Business'), ('IT', 'IT'), ('Engineer', 'Engineer'), ('Doctor', 'Doctor'), ('Government Job', 'Government Job'), ('Home Maker', 'Home Maker'), ('Other', 'Other')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='sibling_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='sibling_occupation',
            field=models.CharField(blank=True, choices=[('Studies', 'Studies'), ('Engineer', 'Engineer'), ('Doctor', 'Doctor'), ('Government Job', 'Government Job'), ('IT', 'IT'), ('Other', 'Other')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='siblings',
            field=models.CharField(choices=[('Single Child', 'Single Child'), ('Yes', 'Yes')], default='Single Child', max_length=20),
        ),
    ]
