# Generated by Django 5.1.4 on 2025-03-04 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matrimony_app', '0007_preferences'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preferences',
            name='max_age',
            field=models.IntegerField(default=50),
        ),
    ]
