# Generated by Django 5.1.4 on 2025-03-04 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matrimony_app', '0008_alter_preferences_max_age'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preferences',
            name='max_age',
        ),
        migrations.RemoveField(
            model_name='preferences',
            name='min_age',
        ),
    ]
