# Generated by Django 5.1.4 on 2025-03-04 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matrimony_app', '0009_remove_preferences_max_age_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Preferences',
        ),
    ]
