# Generated by Django 5.1.4 on 2025-03-05 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matrimony_app', '0010_delete_preferences'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
