# Generated by Django 5.1.4 on 2025-03-10 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matrimony_app', '0012_preferences'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='liked_profiles',
            field=models.ManyToManyField(blank=True, related_name='liked_by', to='matrimony_app.member'),
        ),
    ]
