# Generated by Django 5.1.4 on 2025-03-13 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matrimony_app', '0013_member_liked_profiles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='liked_profiles',
        ),
    ]
