# Generated by Django 5.1.4 on 2025-03-13 11:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matrimony_app', '0014_remove_member_liked_profiles'),
    ]

    operations = [
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('liked_match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes_received', to='matrimony_app.member')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes_given', to='matrimony_app.member')),
            ],
            options={
                'unique_together': {('user', 'liked_match')},
            },
        ),
    ]
