# Generated by Django 5.1.4 on 2025-03-14 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matrimony_app', '0015_like'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Like',
        ),
    ]
