# Generated by Django 5.1.4 on 2025-03-15 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matrimony_app', '0018_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='chat',
        ),
        migrations.RemoveField(
            model_name='message',
            name='sender',
        ),
        migrations.RemoveField(
            model_name='preferences',
            name='user',
        ),
        migrations.DeleteModel(
            name='Chat',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
        migrations.DeleteModel(
            name='Preferences',
        ),
    ]
